# Generated by Django 4.0.1 on 2022-01-21 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from articles.models import Article


def gen_articles(apps, schema_editor):
    # 유저 1
    # 게시글 1
    articles = Article(user_id=1, title="제주도 여행", content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                       contry="대한민국", city="제주", tag="#겨울여행 #3박4일 #액티비티 #가성비여행 #감성여행")
    articles.save()

    # 게시글 2
    articles = Article(user_id=1, title="시카고 여행", content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                       contry="미국", city="시카고", tag="#미국감성 #3박4일 #친구와함께 #시티투어")
    articles.save()

    # 게시글 2
    articles = Article(user_id=1, title="전주 맛집 투어", content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                       contry="대한민국", city="전주", tag="#국내여행 #민속 #혼자 #느긋하게 #맛집투어")
    articles.save()

    # 유저 2
    # 게시글 1
    articles = Article(user_id=2, title="속초로 떠나요", content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                       contry="대한민국", city="속초", tag="#느긋한 #당일치기 #태초마을 #시골감성 #힐링")
    articles.save()

    # 게시글 2
    articles = Article(user_id=2, title="베를린 추천 관광지", content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                       contry="독일", city="베를린", tag="#유럽감성 #장기여행 #시티투어 #연인과함께 #대박추천")
    articles.save()

    #유저 3
    # 게시글 2
    articles = Article(user_id=3, title="파리 여행 with 가이드", content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                       contry="프랑스", city="파리", tag="#유럽감성 #장기여행 #시티투어 #가이드와함께 #대박추천")
    articles.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateField(auto_now=True, verbose_name='수정날짜')),
                ('delete_date', models.DateField(blank=True, null=True, verbose_name='삭제날짜')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('contry', models.CharField(max_length=100, verbose_name='나라')),
                ('city', models.CharField(max_length=100, verbose_name='도시')),
                ('tag', models.CharField(blank=True, max_length=300, null=True, verbose_name='태그')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='리뷰수')),
                ('review_point', models.PositiveIntegerField(default=0, verbose_name='리뷰평점')),
                ('img', models.ImageField(blank=True, upload_to='articles/media/%Y/%m/%d', verbose_name='이미지')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(gen_articles),
    ]
