# Generated by Django 4.0.1 on 2022-01-13 13:14

from django.db import migrations, models

from articles.models import Article
from accounts.models import User


def gen_master(apps, schema_editor):
    # 유저 1
    # 게시글 1

    articles = Article(user_id=1, title="제주도 여행", content="제주 여행 내용", contry="대한민국", city="제주",
                       tag="#겨울여행 #3박4일 #액티비티 #가성비여행 #감성여행")
    articles.save()

    # 게시글 2
    articles = Article(user_id=1, title="시카고 여행", content="시카고 여행 내용", contry="미국", city="시카고",
                       tag="#미국감성 #3박4일 #친구와함께 #시티투어")
    articles.save()

    # 유저 2
    # 게시글 1
    articles = Article(user_id=2, title="속초로 떠나요", content="속초 여행 내용", contry="대한민국", city="속초",
                       tag="#느긋한 #당일치기 #태초마을 #시골감성 #힐링")
    articles.save()

    # 게시글 2
    articles = Article(user_id=2, title="베를린 추천 관광지", content="베를린 여행 내용", contry="독일", city="베를린",
                       tag="#유럽감성 #장기여행 #시티투어 #연인과함께 #대박추천")
    articles.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateField(auto_now=True, verbose_name='수정날짜')),
                ('delete_date', models.DateField(blank=True, null=True, verbose_name='삭제날짜')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('contry', models.CharField(max_length=100, verbose_name='나라')),
                ('city', models.CharField(max_length=100, verbose_name='도시')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='태그')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='리뷰수')),
                ('review_point', models.PositiveIntegerField(default=0, verbose_name='리뷰평점')),
            ],
        ),
        migrations.RunPython(gen_master),
    ]
