# Generated by Django 4.0.1 on 2022-01-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateField(auto_now=True, verbose_name='수정날짜')),
                ('delete_date', models.DateField(blank=True, null=True, verbose_name='삭제날짜')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('contry', models.CharField(max_length=100, verbose_name='나라')),
                ('city', models.CharField(max_length=100, verbose_name='도시')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='태그')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='리뷰수')),
                ('review_point', models.PositiveIntegerField(default=0, verbose_name='리뷰평점')),
            ],
        ),
    ]
