# Generated by Django 4.0.1 on 2022-01-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='이미지'),
        ),
    ]
