# Generated by Django 4.0.1 on 2022-01-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='article',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='리뷰수'),
        ),
        migrations.AddField(
            model_name='article',
            name='review_point',
            field=models.PositiveIntegerField(default=0, verbose_name='리뷰평점'),
        ),
    ]
